### ISSUE TITLE
pretrained models and codes

### ISSUE THREAD

**Issue by betterze** [vglsd/ScaleParty#1]
Dear @vglsd ,

Thank you for sharing this great work. I really like it.

Do you have plan to share the pretrained models and codes? 

Thank you for your help.

Best Wishes,

Zongze

**Comment by entavelis** [comment]
Dear Zongze,

We are planning to release the code and models soon. Stay tuned!

Best,
Evan

**Comment by entavelis** [comment]
Dear Zongze,

The code is out. Enjoy!

Best,
Evan
