### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by sojinleeme** [vglsd/ScaleParty#2]
Dear @vglsd,

I try to download the pretrained model. But, I can't access the site.
Can you share it to the Google Drive?

**Comment by entavelis** [comment]
Dear @sojinleeme ,

I have updated the link to the pretrained model. I hope it works now!

**Comment by sojinleeme** [comment]
Thank you @vglsd!

**Comment by MattLJoslin** [comment]
Hey @entavelis looks like the link may have died again?
